---
- name: Pull Docker image of Calculator
  hosts: localhost
  vars:
    ansible_connection: docker
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: atul55tripathi/calculator:latest
        source: pull
    - name: Running container
      docker_container:
        name: scientific
        image: atul55tripathi/calculator
        state: started
